# Generated by Django 5.2.7 on 2026-03-13 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("company_logo_url", models.URLField(blank=True, null=True)),
                ("location", models.CharField(default="Remote", max_length=255)),
                (
                    "opp_type",
                    models.CharField(
                        choices=[
                            ("JOB", "Full-time Job"),
                            ("INT", "Internship"),
                            ("FRE", "Freelance"),
                        ],
                        default="JOB",
                        max_length=3,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("T1", "Tier 1 (FAANG/Top Product)"),
                            ("T2", "Tier 2 (Mid-Level Product)"),
                            ("T3", "Tier 3 (Service Based)"),
                        ],
                        default="T2",
                        max_length=2,
                    ),
                ),
                ("description", models.TextField()),
                ("requirements", models.TextField(help_text="Comma separated skills")),
                (
                    "package_details",
                    models.CharField(
                        help_text="e.g., 12-15 LPA or 25k/month", max_length=100
                    ),
                ),
                ("deadline", models.DateTimeField()),
                ("apply_link", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Opportunities",
                "ordering": ["-posted_at"],
            },
        ),
        migrations.AlterField(
            model_name="mocktest",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mocktest",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="mocktestquestion",
            name="answer",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="mocktestquestion",
            name="option1",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="mocktestquestion",
            name="option2",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="mocktestquestion",
            name="option3",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="mocktestquestion",
            name="option4",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="SavedOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.opportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
