# Generated by Django 5.2.7 on 2026-03-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_opportunity_alter_mocktest_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="action",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
